export const path = {
  HOME: "/",
  LOGIN: "/login",
  USER_LIST: "/users/list-user",
  BRAND_LIST: "/brand/list-brand",
  BRAND_NEW: "/brand/new-brand",
  COUPON_LIST: "/coupon/list-coupon",
  COUPON_NEW: "/coupon/new-coupon",
  COMMENT_LIST: "/comment/list-comment",
  COMMENT_NOT_CONFIRM: "/comment/notconfirm-comment",
  FEESHIP_LIST: "/feeship/feeship-list",
  ORDER_LIST: "/order/order-list",
  ORDER_DETAIL: "/order/detail/",
  SLIDER_LIST: "/slider/slider-list/",
  SLIDER_NEW: "/slider/slider-new/",
  POST_LIST: "/post/list-post/",
  POST_NEW: "/post/new-post/",
  POST_EDIT: "/post/edit-post/",
  VISITOR: "/visitor",
};
