const response = {
  SUCCESS: "SUCCESS",
  FAIL: "FAIL",
  HAS_USED: "HAS_USED",
  NOT_FOUND: "NOT_FOUND",
  EMAIL_EXIST: "EMAIL_EXIST",
  COUPON_EXIST: "COUPON_EXIST",
  AUTH_SUCCESS: "AUTH_SUCCESS",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
};

export default response;
