const response = {
  SUCCESS: "SUCCESS",
  FAIL: "FAIL",
  HAS_USED: "HAS_USED",
  NOT_FOUND: "NOT_FOUND",
  EMAIL_EXIST: "EMAIL_EXIST",
  PRODUCT_EXIST: "PRODUCT_EXIST",
  COUPON_EXIST: "COUPON_EXIST",
};

export default response;
